### ISSUE TITLE
uberjar command missing to add template directories  

### ISSUE THREAD

**Issue by sombriks** [rife2/bld-spring-boot#2]
i think it affects  version 0.9.4, i have a [sample project](https://github.com/sombriks/sample-htmx-spring) for this issue

**Comment by ethauvin** [comment]
So sorry for the delay in responding. I wasn't getting notifications for some reason.

I tried your project, but there are many dependencies missing. So I didn't get very far.

Isn't the `bootjar` command including the template directories? It's intended to replace the `uberjar` command.

Let me know how I can help to get this going for you.

**Comment by ethauvin** [comment]
Actually, after doing a clean build, I was able to get your project running with `./bld run`. Seems to be running just fine.

**Comment by ethauvin** [comment]
@sombriks I think I found the problem. Try version [0.9.6-SNAPSHOT](https://repo.rife2.com/#/snapshots/com/uwyn/rife2/bld-spring-boot) and let me know if that works for you.

**Comment by sombriks** [comment]
It's alive and kicking now, thanks a lot!

I updated the project!

![image](https://github.com/rife2/bld-spring-boot/assets/556695/93d1169d-2be5-4c02-b290-f1eba96d3ce6)

**Comment by ethauvin** [comment]
@sombriks Version 0.9.6 is out with your fix:

```properties
bld.extensions=com.uwyn.rife2:bld-spring-boot:0.9.6
```


I would also highly suggest adding `autoDownloadPurge = true` to your project's build file. So that dependencies are automatically downloaded.

**Comment by sombriks** [comment]
done!

a side note, bld remains the faster build when the cache kicks in :-)

once again, thanks!

![image](https://github.com/rife2/bld-spring-boot/assets/556695/4390fb22-db7b-4472-94a2-f0226558a794)
